ALTER TABLE apps ADD COLUMN IF NOT EXISTS root_directory TEXT NOT NULL DEFAULT '.';
ALTER TABLE apps ADD COLUMN IF NOT EXISTS install_command TEXT;
ALTER TABLE apps ADD COLUMN IF NOT EXISTS build_command TEXT;
ALTER TABLE apps ADD COLUMN IF NOT EXISTS start_command TEXT;
